// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf0Eg79nzFqzptL21WeU7IY4YsE6jlGco',
    appId: '1:919145093532:web:588d994bd334a3aef5d059',
    messagingSenderId: '919145093532',
    projectId: 'smartfoodcourt-bbcaa',
    authDomain: 'smartfoodcourt-bbcaa.firebaseapp.com',
    storageBucket: 'smartfoodcourt-bbcaa.firebasestorage.app',
    measurementId: 'G-MX2SS2D05Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgMO50Ok5kU4TPS5rZDmNnO4MBVNVYzA',
    appId: '1:919145093532:android:7dee2ce648a350baf5d059',
    messagingSenderId: '919145093532',
    projectId: 'smartfoodcourt-bbcaa',
    storageBucket: 'smartfoodcourt-bbcaa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw3hZgeHooSJXK-k2RAlUHaSbpN_tKIHw',
    appId: '1:919145093532:ios:4e1f784d36d22c0ef5d059',
    messagingSenderId: '919145093532',
    projectId: 'smartfoodcourt-bbcaa',
    storageBucket: 'smartfoodcourt-bbcaa.firebasestorage.app',
    iosBundleId: 'com.example.smartFoodCourt',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw3hZgeHooSJXK-k2RAlUHaSbpN_tKIHw',
    appId: '1:919145093532:ios:4e1f784d36d22c0ef5d059',
    messagingSenderId: '919145093532',
    projectId: 'smartfoodcourt-bbcaa',
    storageBucket: 'smartfoodcourt-bbcaa.firebasestorage.app',
    iosBundleId: 'com.example.smartFoodCourt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf0Eg79nzFqzptL21WeU7IY4YsE6jlGco',
    appId: '1:919145093532:web:7afe6ad0b130a388f5d059',
    messagingSenderId: '919145093532',
    projectId: 'smartfoodcourt-bbcaa',
    authDomain: 'smartfoodcourt-bbcaa.firebaseapp.com',
    storageBucket: 'smartfoodcourt-bbcaa.firebasestorage.app',
    measurementId: 'G-2RMFY954LG',
  );
}
